
export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";
export const MOVE_NEXT_SLIDE = "MOVE_NEXT_SLIDE";
export const MOVE_PREV_SLIDE = "MOVE_PREV_SLIDE";
export const CONVERT_MARKDOWN_TO_HTML = "CONVERT_MARKDOWN_TO_HTML";
