
export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";
export const MOVE_NEXT_SLIDE = "MOVE_NEXT_SLIDE";
export const MOVE_PREV_SLIDE = "MOVE_PREV_SLIDE";
export const CHANGE_PROGRESSBAR_ON = "CHANGE_PROGRESSBAR_ON";
export const CHANGE_PROGRESSBAR_OFF = "CHANGE_PROGRESSBAR_OFF";
export const CREATE_SLIDES = "CREATE_SLIDES";
export const CHANGE_THEME_DARK = "CHANGE_THEME_DARK";
export const CHANGE_THEME_SIMPLE = "CHANGE_THEME_SIMPLE";
export const CHANGE_THEME_CLEARSKY = "CHANGE_THEME_CLEARSKY";

// テーマ変更のための定数
export const THEME_SIMPLE = "THEME_SIMPLE";
export const THEME_RED = "THEME_RED";
export const THEME_DARK = "THEME_DARK";
export const THEME_CLEARSKY = "THEME_CLEARSKY";
